### PR TITLE
Fix `README` typos identified by IntelliJ

### PR DESCRIPTION
**Pull request by JackPGreen**
Fix `README` typos identified by IntelliJ (e.g. "hazelast" -> "hazelcast")

### CODE REVIEW

**Comment by JackPGreen** [comment]
PR builder failure caused by https://github.com/hazelcast/hazelcast-jet-demos/issues/153

**Comment by JackPGreen** [comment]
.

**Comment by JackPGreen** [comment]
Re-open

**Comment by nishaatr** [comment]
Reopen

**Pull request closed without merging**
